# Should MobEffects check for updates?
AutoCheckForUpdates: true
# Which Worlds do you want MobEffects enabled in?
Worlds:
- world
- world_nether
- world_the_end
# Should MobEffects control the spawns on your server? Each mob can be configured separately.
ManipulateSpawns: false